export const changelog = [
  {
    title: "Add Security functions and new Page",
    version: "0.4",
    updates: [
      "Add new role system",
      "Add last logins ip lookup (country, region)",
      "Add Social-Media calendar Page",
      "Add new contacts column `Standhelfer` and only these are selectable at Infostand",
      "Add newest changelog on Dashboard",
      "Add color legend for the Kanbanboard and Social-Media calendar",
      "Fix errors in the time and date output",
      "Fix error when changing password",
      "Fix constand search problems",
    ],
  },
  {
    title: "Add E-Mail and Security functions",
    version: "0.3",
    updates: [
      "Add E-Mail transmitter",
      "Add Password reset function at login page",
      "Add Account will be blocked if the password is entered incorrectly 3 times within 5 minutes",
      "Add different Backend Security features",
      "Add Con-Stand Page",
      "Add Clicking on the website or Instagram name opens the corresponding page in a new tab (at contacts, con-stand)",
      "Add Account has been blocked due to failed login E-Mail to user",
      "Add Hide unused fields when viewing contact",
      "Add first Dashboard module (next Cons)",
    ],
  },
  {
    title: "Add new Pages and functions",
    version: "0.2",
    updates: [
      "Add Contact Page",
      "Add Password show Buttons",
      "Add Password guidelines",
      "Add Delete subtasks when creating a task",
      "Add Show Reported Bugs",
      "Add Light/Dark-mode",
      "Fix Tasks without subtasks suddenly have 1 subtask",
      "Fix Confirm login with enter key",
      "Fix BugReport Automatic reload of the bug list when a new Bug is added",
      "Fix New contacts cannot be changed directly after creation",
      "Fix Login Session expires time problems",
      "Fix some Graphic Bugs",
      "Fix Last logins IP-Adress faulty",
    ],
  },
  {
    title: "Initiale Version",
    version: "0.1",
    updates: [
      "Add Profilepage with E-Mail and Password change",
      "Add Kanbanboard",
      "Add Adminboard",
      "Add Changelog",
      "Add Comming Soon",
      "Add Bug Report",
      "Add YumeKai Survey Evaluation",
    ],
  },
];
